### ISSUE TITLE
Camera controls are not working well

### ISSUE THREAD

**Issue by jailln** [MEPP-team/UDV#22]
## The problem

Camera controls are not working normally and movements in the 3D scene are not intuitive. This is most likely due to a picking problem in iTowns which has been resolved in the last release.

## Actions

Rebase [Itowns - 3D Tiles temporal](https://github.com/jailln/itowns/tree/3dtiles-temporal) on the last version of iTowns.

**Comment by EricBoix** [comment]
Done in PR #33 .
