### ISSUE TITLE
Factorize configuration files

### ISSUE THREAD

**Issue by jailln** [MEPP-team/UDV#85]
There is a lot of configuration files in UDV (basically one per example demo plus one per module demo and per extension demo) with a lot of duplicates in these files. 

They should be factorized (e.g. one per module) and then combined for example demos using multiple modules.

**Comment by Crejak** [comment]
A first approach would be to have one global config file, which all demos can refer to. Having multiple files that can be merged seem less ergonomic (someone who wants to create a demo would have to specify the location of each config file, without forgetting one ?).

**Comment by jailln** [comment]
It works for me.

**Comment by jailln** [comment]
Closed with #86
